name: Run Nyasha Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  start-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Restore Baileys auth
        uses: actions/cache@v3
        with:
          path: baileysauthinfo
          key: ${{ runner.os }}-baileys-${{ hashFiles('baileysauthinfo/**') }}

      - name: Install dependencies
        run: npm ci

      - name: Create env file
        run: echo "GEMINIAPIKEY=${{ secrets.GEMINIAPIKEY }}" > .env

      - name: Start Nyasha Bot
        env:
          GEMINIAPIKEY: ${{ secrets.GEMINIAPIKEY }}
        run: node index.js